# Generated by Django 5.0.6 on 2024-06-30 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video_id', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='courses_logo/')),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.audience')),
            ],
        ),
    ]
