# Generated by Django 5.0.6 on 2024-07-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_audience_slug_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='files_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
